name: Hight_blood_pressure CICD
permissions: write-all
# 觸發條件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
# 執行一項或多項任務
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
 
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN_TEST }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
 
    # 建立環境
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Program/requirement.txt
    - name: Infernece
      run : |
        cd Program
        python XGB_inference.py
        python RF_inference.py
        python DTB_inference.py
        cd ..
    - name: CD
      run: |
          cd C:\Users\oplab\Desktop\CICD_test
          git pull https://github.com/fenofista/CICD_test.git
          cd Program
          python main.py
    - name: commit
      run: |
          cd C:\Users\oplab\Desktop\CICD_test
          git config --local user.email "s960068sss@github.com"
          git config --local user.name "fenofista"
          git add .
          git commit -m "training"
          git push
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GH_TOKEN_TEST }}
#         branch: main

